version: '3.8'

services:
  app:
    build: .
    container_name: grao_nobre_app
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    restart: always
